#ifndef LTS_CONSTANTS
#define LTS_CONSTANTS

#define DAYS_IN_WEEK 7
#define TIMEZONE -5

#define SUNDAY 0
#define MONDAY 1
#define TUESDAY 2
#define WEDNESDAY 3
#define THURSDAY 4
#define FRIDAY 5
#define SATURDAY 6

#define JANUARY 0
#define FEBRUARY 1
#define MARCH 2
#define APRIL 3
#define MAY 4
#define JUNE 5
#define JULY 6
#define AUGUST 7
#define SEPTEMBER 8
#define OCTOBER 9
#define NOVEMBER 10
#define DECEMBER 11

#define JANUARY_DAYS 31
#define FEBRUARY_DAYS 28
#define MARCH_DAYS 31
#define APRIL_DAYS 30
#define MAY_DAYS 31
#define JUNE_DAYS 30
#define JULY_DAYS 31
#define AUGUST_DAYS 31
#define SEPTEMBER_DAYS 30
#define OCTOBER_DAYS 31
#define NOVEMBER_DAYS 30
#define DECEMBER_DAYS 31

namespace ts{
enum class TaskStatus {
	FINISHED,
	INIT_ERROR,
	EXEC_ERROR,
	QUEUED,
	RUNNING
};

enum class TaskValidate {
	OK,
	MISSING_NAME_KEYVAL,
	MISSING_SCRIPTFN_KEYVAL,
	MISSING_FREQUENCY_KEYVAL,
	MISSING_DATETIME_KEYVAL,
	SCRIPT_NOT_FOUND,
	BAD_FREQUENCY_VALUE,
    BAD_DATETIME_VALUE,
    MISSING_DATETIME_VALUE
};

enum class DatetimeValidate{
    OK,
    BAD_HMS_LENGTH,
    BAD_YYYYMMDD_LENGTH,
    BAD_MMDD_LENGTH,
    BAD_NUMBER_CHARACTER,
    BAD_APHABETIC_CHARACTER,
    MISSING_COLON,
    MISSING_DASH,
    MISSING_SPACE,
    BAD_WDAY,
    YEAR_OUT_OF_RANGE,
    MONTH_OUT_OF_RANGE,
    DAY_OUT_OF_RANGE,
    HOURS_OUT_OF_RANGE,
    MINUTES_OUT_OF_RANGE,
    SECONDS_OUT_OF_RANGE,
    INVALID_DATETIME_INPUT
};

enum class DatetimeFormat {
    YYYYMMDD_HHMMSS = 32,
    WDAY6_HHMMSS = 68,
    WDAY7_HHMMSS = 76,
    WDAY8_HHMMSS = 84,
    WDAY9_HHMMSS = 92,
    WDAY_HHMMSS = 44,
    YYYYMMDD = 12,
    HHMMSS = 14,
    INVALID_DATE_FORMAT = -1
};

enum class EventType{
    INFO,
    WARNING,
    ERROR
};

}

#endif